---
title: "Tidy datasets"
author: "Jay Hesselberth"
date: "December 27, 2015"
output:
  md_document:
    variant: markdown_github
    toc: true
    toc_depth: 2
---

# Overview

Tidy up all of the R builtin datasets.

```{r library, message=FALSE, warning=FALSE}
library(tidyr)
library(dplyr)

knitr::opts_chunk$set(comment='#>')

format_strs <- function(strings, sep='.', ...) {
  strings %>%
    stringr::str_to_lower() %>%
    stringr::str_replace_all(' ', sep)
}

```

### ability

```{r ability.cov}
ability.cov_tidy <- ability.cov %>%
  as.data.frame() %>%
  select(-n.obs, -center) %>%
  mutate(test = rownames(.)) %>%
  gather(cov, value, -test) %>%
  tbl_df()

ability.cov_tidy 
```

### airmiles

```{r airmiles}
airmiles_tidy <- airmiles %>%
  as.data.frame() %>%
  setNames('airmiles') %>%
  mutate(year = time(airmiles)) %>%
  tbl_df()

airmiles_tidy
```

### AirPassengers

```{r AirPassengers}
# gawd time series are awful ...
# from http://stackoverflow.com/questions/5331901/transforming-a-ts-in-a-data-frame-and-back

dmn <- list(month.abb, unique(floor(time(AirPassengers))))
AirPassengers_df <- tbl_df(data.frame(matrix(AirPassengers, 12, dimnames = dmn)))

AirPassengers_tidy <- AirPassengers_df %>%
  mutate(month = rownames(.)) %>%
  gather(year, value, -month)

AirPassengers_tidy
```

### austres

```{r austres}
# Figure out how to get the 'Qtr1' ... colnames
```

### beavers

```{r beavers}
# Combine the beaver1 and beaver2 datasets ...
beaver1_tidy <- beaver1 %>%
  mutate(obs = seq_len(n())) %>%
  gather(key, value, -obs) %>%
  mutate(beaver = '1')

beaver2_tidy <- beaver2 %>%
  mutate(obs = seq_len(n())) %>%
  gather(key, value, -obs) %>%
  mutate(beaver = '2')

beavers_tidy <- rbind_list(beaver1_tidy, beaver2_tidy)

beavers_tidy
```

### BOD

```{r BOD}
BOD_tidy <- BOD %>% tbl_df %>%
  mutate(obs = seq_len(n())) %>%
  gather(key, value, -obs)

BOD_tidy
```

### cars

```{r cars}
cars_tidy <- cars %>% tbl_df %>%
  mutate(obs = seq_len(n())) %>%
  gather(key, value, -obs)

cars_tidy
```

### ChickWeight

```{r ChickWeight, warning=FALSE}
ChickWeight_tidy <- ChickWeight %>%
  gather(key, value, -Chick, convert = TRUE) %>%
  tbl_df

ChickWeight_tidy
```

### chickwts

```{r chickwts}
# `chickwts` already tidy
```

### CO2

```{r CO2}
# `CO2` already tidy
```

### DNase

```{r DNase}
# `DNase` already tidy
```

### esoph

```{r esoph}
# `esoph` already tidy
```

### faithful

```{r faithful}
# `faithful` already tidy
```

### Formaldehyde

```{r Formaldehyde}
# `Formaldehyde` already tidy
```

### mtcars

```{r mtcars}
mtcars_tidy <- mtcars %>%
  mutate(car = format_strs(rownames(.))) %>% 
  gather(key, value, -car)   
```
